package br.ufes.analisador.lexico.view;

import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JToolBar;

public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExecutar = new javax.swing.JButton();
        pnlCodigo = new javax.swing.JPanel();
        scrTbSimbolos = new javax.swing.JScrollPane();
        tblSimbolos = new javax.swing.JTable();
        lblTbSimbolos = new javax.swing.JLabel();
        lblCodigoFonte = new javax.swing.JLabel();
        scrSaida = new javax.swing.JScrollPane();
        epnSaida = new javax.swing.JEditorPane();
        lblSaida = new javax.swing.JLabel();
        manuBar = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        itmSalvarComo = new javax.swing.JMenuItem();
        itmFechar = new javax.swing.JMenuItem();
        mnOpcoes = new javax.swing.JMenu();
        chkItmAnaliseAuto = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnNovo);

        btnAbrir.setText("Abrir");
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnAbrir);

        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnSalvar);
        toolBar.add(jSeparator1);

        btnUndo.setText("<-");
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnUndo);

        btnRedo.setText("->");
        btnRedo.setFocusable(false);
        btnRedo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRedo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnRedo);
        toolBar.add(jSeparator2);

        btnExecutar.setText("Executar");
        btnExecutar.setFocusable(false);
        btnExecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnExecutar);

        javax.swing.GroupLayout pnlCodigoLayout = new javax.swing.GroupLayout(pnlCodigo);
        pnlCodigo.setLayout(pnlCodigoLayout);
        pnlCodigoLayout.setHorizontalGroup(
            pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCodigoLayout.setVerticalGroup(
            pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Linhas", "Coluna", "Nome", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTbSimbolos.setViewportView(tblSimbolos);

        lblTbSimbolos.setText("Tabela de Símbolos");

        lblCodigoFonte.setText("Código Fonte");

        scrSaida.setViewportView(epnSaida);

        lblSaida.setText("Saída");

        mnArquivo.setText("Arquivo");

        itmSalvarComo.setText("Salvar Como");
        mnArquivo.add(itmSalvarComo);

        itmFechar.setText("Fechar");
        mnArquivo.add(itmFechar);

        manuBar.add(mnArquivo);

        mnOpcoes.setText("Opções");

        chkItmAnaliseAuto.setSelected(true);
        chkItmAnaliseAuto.setText("Análise Automática");
        mnOpcoes.add(chkItmAnaliseAuto);

        manuBar.add(mnOpcoes);

        setJMenuBar(manuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoFonte)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTbSimbolos)
                            .addComponent(scrTbSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTbSimbolos)
                    .addComponent(lblCodigoFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrTbSimbolos, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(pnlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAbrir() {
        return btnAbrir;
    }

    public void setBtnAbrir(JButton btnAbrir) {
        this.btnAbrir = btnAbrir;
    }

    public JButton getBtnExecutar() {
        return btnExecutar;
    }

    public void setBtnExecutar(JButton btnExecutar) {
        this.btnExecutar = btnExecutar;
    }

    public JButton getBtnNovo() {
        return btnNovo;
    }

    public void setBtnNovo(JButton btnNovo) {
        this.btnNovo = btnNovo;
    }

    public JButton getBtnRedo() {
        return btnRedo;
    }

    public void setBtnRedo(JButton btnRedo) {
        this.btnRedo = btnRedo;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }

    public JButton getBtnUndo() {
        return btnUndo;
    }

    public void setBtnUndo(JButton btnUndo) {
        this.btnUndo = btnUndo;
    }

    public JCheckBoxMenuItem getChkItmAnaliseAuto() {
        return chkItmAnaliseAuto;
    }

    public void setChkItmAnaliseAuto(JCheckBoxMenuItem chkItmAnaliseAuto) {
        this.chkItmAnaliseAuto = chkItmAnaliseAuto;
    }

    public JEditorPane getEpnSaida() {
        return epnSaida;
    }

    public void setEpnSaida(JEditorPane epnSaida) {
        this.epnSaida = epnSaida;
    }

    public JMenuItem getItmFechar() {
        return itmFechar;
    }

    public void setItmFechar(JMenuItem itmFechar) {
        this.itmFechar = itmFechar;
    }

    public JMenuItem getItmSalvarComo() {
        return itmSalvarComo;
    }

    public void setItmSalvarComo(JMenuItem itmSalvarComo) {
        this.itmSalvarComo = itmSalvarComo;
    }

    public JToolBar.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JToolBar.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JLabel getLblCodigoFonte() {
        return lblCodigoFonte;
    }

    public void setLblCodigoFonte(JLabel lblCodigoFonte) {
        this.lblCodigoFonte = lblCodigoFonte;
    }

    public JLabel getLblSaida() {
        return lblSaida;
    }

    public void setLblSaida(JLabel lblSaida) {
        this.lblSaida = lblSaida;
    }

    public JLabel getLblTbSimbolos() {
        return lblTbSimbolos;
    }

    public void setLblTbSimbolos(JLabel lblTbSimbolos) {
        this.lblTbSimbolos = lblTbSimbolos;
    }

    public JMenuBar getManuBar() {
        return manuBar;
    }

    public void setManuBar(JMenuBar manuBar) {
        this.manuBar = manuBar;
    }

    public JMenu getMnArquivo() {
        return mnArquivo;
    }

    public void setMnArquivo(JMenu mnArquivo) {
        this.mnArquivo = mnArquivo;
    }

    public JMenu getMnOpcoes() {
        return mnOpcoes;
    }

    public void setMnOpcoes(JMenu mnOpcoes) {
        this.mnOpcoes = mnOpcoes;
    }

    public JPanel getPnlCodigo() {
        return pnlCodigo;
    }

    public void setPnlCodigo(JPanel pnlCodigo) {
        this.pnlCodigo = pnlCodigo;
    }

    public JScrollPane getScrSaida() {
        return scrSaida;
    }

    public void setScrSaida(JScrollPane scrSaida) {
        this.scrSaida = scrSaida;
    }

    public JScrollPane getScrTbSimbolos() {
        return scrTbSimbolos;
    }

    public void setScrTbSimbolos(JScrollPane scrTbSimbolos) {
        this.scrTbSimbolos = scrTbSimbolos;
    }

    public JTable getTblSimbolos() {
        return tblSimbolos;
    }

    public void setTblSimbolos(JTable tblSimbolos) {
        this.tblSimbolos = tblSimbolos;
    }

    public JToolBar getToolBar() {
        return toolBar;
    }

    public void setToolBar(JToolBar toolBar) {
        this.toolBar = toolBar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUndo;
    private javax.swing.JCheckBoxMenuItem chkItmAnaliseAuto;
    private javax.swing.JEditorPane epnSaida;
    private javax.swing.JMenuItem itmFechar;
    private javax.swing.JMenuItem itmSalvarComo;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JLabel lblCodigoFonte;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTbSimbolos;
    private javax.swing.JMenuBar manuBar;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnOpcoes;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JScrollPane scrSaida;
    private javax.swing.JScrollPane scrTbSimbolos;
    private javax.swing.JTable tblSimbolos;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
