// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/br/ufes/analisador/lexico/jflex/cmenosmenos.lex

package br.ufes.analisador.lexico.jflex;

import br.ufes.analisador.lexico.analisador.ErroAnalisado;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\3\u1f00\1\u4000"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u1f00\1\u4900\1\u1f00\1\u4a00\1\u4b00\2\u1f00\3\u0100\1\u4c00"+
    "\1\u4d00\1\u4e00\12\u1f00\4\u0100\1\u4f00\17\u1f00\2\u0100\1\u5000"+
    "\41\u1f00\2\u0100\1\u5100\1\u5200\3\u1f00\1\u5300\27\u0100\1\u5400"+
    "\2\u0100\1\u5500\45\u1f00\1\u0100\1\u5600\1\u5700\11\u1f00\1\u5800"+
    "\24\u1f00\1\u5900\1\u5a00\1\u1f00\1\u5b00\1\u5c00\1\u5d00\1\u5e00"+
    "\2\u1f00\1\u5f00\5\u1f00\1\u6000\7\u1f00\1\u6100\1\u6200\4\u1f00"+
    "\1\u6300\21\u1f00\246\u0100\1\u6400\20\u0100\1\u6500\1\u6600\25\u0100"+
    "\1\u6700\34\u0100\1\u6800\14\u1f00\2\u0100\1\u6900\u0b05\u1f00\1\u6a00"+
    "\1\u6b00\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\16\0\4\3"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\3\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\11\25\1\3\1\26\1\27\1\30\1\31\2\3"+
    "\1\32\2\11\1\33\11\11\1\34\1\35\2\11\1\36"+
    "\10\11\1\37\1\40\1\41\1\3\1\11\1\3\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\11\1\53\1\54\1\11\1\55\1\56\1\57\1\11"+
    "\1\60\1\61\1\62\1\63\1\64\1\11\1\65\2\11"+
    "\1\66\1\67\1\70\1\3\41\0\2\3\4\11\4\3"+
    "\1\11\2\3\1\0\7\3\1\11\4\3\1\11\5\3"+
    "\27\11\1\3\37\11\1\3\u01ca\11\4\3\14\11\16\3"+
    "\5\11\7\3\1\11\1\3\1\11\21\3\160\0\5\11"+
    "\1\3\2\11\2\3\4\11\1\3\1\11\6\3\1\11"+
    "\1\3\3\11\1\3\1\11\1\3\24\11\1\3\123\11"+
    "\1\3\213\11\1\3\5\0\2\3\246\11\1\3\46\11"+
    "\2\3\1\11\7\3\47\11\7\3\1\11\1\3\55\0"+
    "\1\3\1\0\1\3\2\0\1\3\2\0\1\3\1\0"+
    "\10\3\33\11\5\3\3\11\15\3\6\0\5\3\1\11"+
    "\4\3\13\0\1\3\1\0\3\3\53\11\37\0\4\3"+
    "\2\11\1\0\143\11\1\3\1\11\10\0\1\3\6\0"+
    "\2\11\2\0\1\3\4\0\2\11\12\0\3\11\2\3"+
    "\1\11\17\3\1\0\1\11\1\0\36\11\33\0\2\3"+
    "\131\11\13\0\1\11\16\3\12\0\41\11\11\0\2\11"+
    "\4\3\1\11\5\3\26\11\4\0\1\11\11\0\1\11"+
    "\3\0\1\11\5\0\22\3\31\11\3\0\4\3\13\11"+
    "\65\3\25\11\1\3\10\11\26\3\60\0\66\11\3\0"+
    "\1\11\22\0\1\11\7\0\12\11\2\0\2\3\12\0"+
    "\1\3\20\11\3\0\1\3\10\11\2\3\2\11\2\3"+
    "\26\11\1\3\7\11\1\3\1\11\3\3\4\11\2\3"+
    "\1\0\1\11\7\0\2\3\2\0\2\3\3\0\1\11"+
    "\10\3\1\0\4\3\2\11\1\3\3\11\2\0\2\3"+
    "\12\0\4\11\7\3\2\11\4\3\3\0\1\3\6\11"+
    "\4\3\2\11\2\3\26\11\1\3\7\11\1\3\2\11"+
    "\1\3\2\11\1\3\2\11\2\3\1\0\1\3\5\0"+
    "\4\3\2\0\2\3\3\0\3\3\1\0\7\3\4\11"+
    "\1\3\1\11\7\3\14\0\3\11\1\0\13\3\3\0"+
    "\1\3\11\11\1\3\3\11\1\3\26\11\1\3\7\11"+
    "\1\3\2\11\1\3\5\11\2\3\1\0\1\11\10\0"+
    "\1\3\3\0\1\3\3\0\2\3\1\11\17\3\2\11"+
    "\2\0\2\3\12\0\1\3\1\11\7\3\1\11\6\0"+
    "\1\3\3\0\1\3\10\11\2\3\2\11\2\3\26\11"+
    "\1\3\7\11\1\3\2\11\1\3\5\11\2\3\1\0"+
    "\1\11\7\0\2\3\2\0\2\3\3\0\10\3\2\0"+
    "\4\3\2\11\1\3\3\11\2\0\2\3\12\0\1\3"+
    "\1\11\20\3\1\0\1\11\1\3\6\11\3\3\3\11"+
    "\1\3\4\11\3\3\2\11\1\3\1\11\1\3\2\11"+
    "\3\3\2\11\3\3\3\11\3\3\14\11\4\3\5\0"+
    "\3\3\3\0\1\3\4\0\2\3\1\11\6\3\1\0"+
    "\16\3\12\0\11\3\1\11\6\3\4\0\1\3\10\11"+
    "\1\3\3\11\1\3\27\11\1\3\20\11\3\3\1\11"+
    "\7\0\1\3\3\0\1\3\4\0\7\3\2\0\1\3"+
    "\3\11\5\3\2\11\2\0\2\3\12\0\20\3\1\11"+
    "\3\0\1\3\10\11\1\3\3\11\1\3\27\11\1\3"+
    "\12\11\1\3\5\11\2\3\1\0\1\11\7\0\1\3"+
    "\3\0\1\3\4\0\7\3\2\0\7\3\1\11\1\3"+
    "\2\11\2\0\2\3\12\0\1\3\2\11\15\3\4\0"+
    "\1\3\10\11\1\3\3\11\1\3\51\11\2\0\1\11"+
    "\7\0\1\3\3\0\1\3\4\0\1\11\5\3\3\11"+
    "\1\0\7\3\3\11\2\0\2\3\12\0\12\3\6\11"+
    "\2\3\2\0\1\3\22\11\3\3\30\11\1\3\11\11"+
    "\1\3\1\11\2\3\7\11\3\3\1\0\4\3\6\0"+
    "\1\3\1\0\1\3\10\0\6\3\12\0\2\3\2\0"+
    "\15\3\60\11\1\0\2\11\7\0\4\3\10\11\10\0"+
    "\1\3\12\0\47\3\2\11\1\3\1\11\2\3\2\11"+
    "\1\3\1\11\2\3\1\11\6\3\4\11\1\3\7\11"+
    "\1\3\3\11\1\3\1\11\1\3\1\11\2\3\2\11"+
    "\1\3\4\11\1\0\2\11\6\0\1\3\2\0\1\11"+
    "\2\3\5\11\1\3\1\11\1\3\6\0\2\3\12\0"+
    "\2\3\4\11\40\3\1\11\27\3\2\0\6\3\12\0"+
    "\13\3\1\0\1\3\1\0\1\3\1\0\4\3\2\0"+
    "\10\11\1\3\44\11\4\3\24\0\1\3\2\0\5\11"+
    "\13\0\1\3\44\0\11\3\1\0\71\3\53\11\24\0"+
    "\1\11\12\0\6\3\6\11\4\0\4\11\3\0\1\11"+
    "\3\0\2\11\7\0\3\11\4\0\15\11\14\0\1\11"+
    "\17\0\2\3\46\11\1\3\1\11\5\3\1\11\2\3"+
    "\53\11\1\3\115\11\1\3\4\11\2\3\7\11\1\3"+
    "\1\11\1\3\4\11\2\3\51\11\1\3\4\11\2\3"+
    "\41\11\1\3\4\11\2\3\7\11\1\3\1\11\1\3"+
    "\4\11\2\3\17\11\1\3\71\11\1\3\4\11\2\3"+
    "\103\11\2\3\3\0\40\3\20\11\20\3\126\11\2\3"+
    "\6\11\3\3\u016c\11\2\3\21\11\1\3\32\11\5\3"+
    "\113\11\3\3\13\11\7\3\15\11\1\3\4\11\3\0"+
    "\13\3\22\11\3\0\13\3\22\11\2\0\14\3\15\11"+
    "\1\3\3\11\1\3\2\0\14\3\64\11\40\0\3\3"+
    "\1\11\3\3\2\11\1\0\2\3\12\0\41\3\4\0"+
    "\1\3\12\0\6\3\130\11\10\3\5\11\2\0\42\11"+
    "\1\0\1\11\5\3\106\11\12\3\37\11\1\3\14\0"+
    "\4\3\14\0\12\3\12\0\36\11\2\3\5\11\13\3"+
    "\54\11\4\3\32\11\6\3\12\0\46\3\27\11\5\0"+
    "\4\3\65\11\12\0\1\3\35\0\2\3\13\0\6\3"+
    "\12\0\15\3\1\11\10\3\16\0\102\3\5\0\57\11"+
    "\21\0\7\11\4\3\12\0\21\3\11\0\14\3\3\0"+
    "\36\11\15\0\2\11\12\0\54\11\16\0\14\3\44\11"+
    "\24\0\10\3\12\0\3\3\3\11\12\0\44\11\2\3"+
    "\11\11\107\3\3\0\1\3\25\0\4\11\1\0\4\11"+
    "\3\0\2\11\3\0\6\3\300\11\72\0\1\3\5\0"+
    "\26\11\2\3\6\11\2\3\46\11\2\3\6\11\2\3"+
    "\10\11\1\3\1\11\1\3\1\11\1\3\1\11\1\3"+
    "\37\11\2\3\65\11\1\3\7\11\1\3\1\11\3\3"+
    "\3\11\1\3\7\11\3\3\4\11\2\3\6\11\4\3"+
    "\15\11\5\3\3\11\1\3\7\11\16\3\5\0\32\3"+
    "\5\0\20\3\2\11\23\3\1\11\13\3\5\0\1\3"+
    "\12\0\1\3\1\11\15\3\1\11\20\3\15\11\3\3"+
    "\40\11\20\3\15\0\4\3\1\0\3\3\14\0\21\3"+
    "\1\11\4\3\1\11\2\3\12\11\1\3\1\11\3\3"+
    "\5\11\6\3\1\11\1\3\1\11\1\3\1\11\1\3"+
    "\4\11\1\3\13\11\2\3\4\11\5\3\5\11\4\3"+
    "\1\11\21\3\51\11\u0177\3\57\11\1\3\57\11\1\3"+
    "\205\11\6\3\4\11\3\0\2\11\14\3\46\11\1\3"+
    "\1\11\5\3\1\11\2\3\70\11\7\3\1\11\17\3"+
    "\1\0\27\11\11\3\7\11\1\3\7\11\1\3\7\11"+
    "\1\3\7\11\1\3\7\11\1\3\7\11\1\3\7\11"+
    "\1\3\7\11\1\3\40\0\57\3\1\11\325\3\3\11"+
    "\31\3\11\11\6\0\1\3\5\11\2\3\5\11\4\3"+
    "\126\11\2\3\2\0\2\3\3\11\1\3\132\11\1\3"+
    "\4\11\5\3\52\11\2\3\136\11\21\3\33\11\65\3"+
    "\306\11\112\3\353\11\25\3\215\11\103\3\56\11\2\3"+
    "\15\11\3\3\20\11\12\0\2\11\24\3\57\11\1\0"+
    "\4\3\12\0\1\3\37\11\2\0\120\11\2\0\45\3"+
    "\11\11\2\3\147\11\2\3\44\11\1\3\10\11\77\3"+
    "\13\11\1\0\3\11\1\0\4\11\1\0\27\11\5\0"+
    "\20\3\1\11\7\3\64\11\14\3\2\0\62\11\22\0"+
    "\12\3\12\0\6\3\22\0\6\11\3\3\1\11\1\3"+
    "\1\11\2\3\12\0\34\11\10\0\2\3\27\11\15\0"+
    "\14\3\35\11\3\3\4\0\57\11\16\0\16\3\1\11"+
    "\12\0\6\3\5\11\1\0\12\11\12\0\5\11\1\3"+
    "\51\11\16\0\11\3\3\11\1\0\10\11\2\0\2\3"+
    "\12\0\6\3\27\11\3\3\1\11\3\0\62\11\1\0"+
    "\1\11\3\0\2\11\2\0\5\11\2\0\1\11\1\0"+
    "\1\11\30\3\3\11\2\3\13\11\5\0\2\3\3\11"+
    "\2\0\12\3\6\11\2\3\6\11\2\3\6\11\11\3"+
    "\7\11\1\3\7\11\1\3\53\11\1\3\12\11\12\3"+
    "\163\11\10\0\1\3\2\0\2\3\12\0\6\3\244\11"+
    "\14\3\27\11\4\3\61\11\4\3\156\11\2\3\152\11"+
    "\46\3\7\11\14\3\5\11\5\3\1\11\1\0\12\11"+
    "\1\3\15\11\1\3\5\11\1\3\1\11\1\3\2\11"+
    "\1\3\2\11\1\3\154\11\41\3\153\11\22\3\100\11"+
    "\2\3\66\11\50\3\15\11\3\3\20\0\20\3\20\0"+
    "\3\3\2\11\30\3\3\11\31\3\1\11\6\3\5\11"+
    "\1\3\207\11\2\3\1\0\4\3\1\11\13\3\12\0"+
    "\7\3\32\11\4\3\1\11\1\3\32\11\13\3\131\11"+
    "\3\3\6\11\2\3\6\11\2\3\6\11\2\3\3\11"+
    "\3\3\2\11\3\3\2\11\22\3\3\0\4\3\14\11"+
    "\1\3\32\11\1\3\23\11\1\3\2\11\1\3\17\11"+
    "\2\3\16\11\42\3\173\11\105\3\65\11\210\3\1\0"+
    "\202\3\35\11\3\3\61\11\17\3\1\0\37\3\40\11"+
    "\15\3\36\11\5\3\46\11\5\0\5\3\36\11\2\3"+
    "\44\11\4\3\10\11\1\3\5\11\52\3\236\11\2\3"+
    "\12\0\6\3\44\11\4\3\44\11\4\3\50\11\10\3"+
    "\64\11\234\3\67\11\11\3\26\11\12\3\10\11\230\3"+
    "\6\11\2\3\1\11\1\3\54\11\1\3\2\11\3\3"+
    "\1\11\2\3\27\11\12\3\27\11\11\3\37\11\101\3"+
    "\23\11\1\3\2\11\12\3\26\11\12\3\32\11\106\3"+
    "\70\11\6\3\2\11\100\3\1\11\3\0\1\3\2\0"+
    "\5\3\4\0\4\11\1\3\3\11\1\3\33\11\4\3"+
    "\3\0\4\3\1\0\40\3\35\11\3\3\35\11\43\3"+
    "\10\11\1\3\34\11\2\0\31\3\66\11\12\3\26\11"+
    "\12\3\23\11\15\3\22\11\156\3\111\11\67\3\63\11"+
    "\15\3\63\11\15\3\3\0\65\11\17\0\37\3\12\0"+
    "\17\3\4\0\55\11\13\0\2\3\1\0\22\3\31\11"+
    "\7\3\12\0\6\3\3\0\44\11\16\0\1\3\12\0"+
    "\20\3\43\11\1\0\2\3\1\11\11\3\3\0\60\11"+
    "\16\0\4\11\5\3\3\0\3\3\12\0\1\11\1\3"+
    "\1\11\43\3\22\11\1\3\31\11\14\0\6\3\1\0"+
    "\101\3\7\11\1\3\1\11\1\3\4\11\1\3\17\11"+
    "\1\3\12\11\7\3\57\11\14\0\5\3\12\0\6\3"+
    "\4\0\1\3\10\11\2\3\2\11\2\3\26\11\1\3"+
    "\7\11\1\3\2\11\1\3\5\11\2\3\1\0\1\11"+
    "\7\0\2\3\2\0\2\3\3\0\2\3\1\11\6\3"+
    "\1\0\5\3\5\11\2\0\2\3\7\0\3\3\5\0"+
    "\213\3\65\11\22\0\4\11\5\3\12\0\46\3\60\11"+
    "\24\0\2\11\1\3\1\11\10\3\12\0\246\3\57\11"+
    "\7\0\2\3\11\0\27\3\4\11\2\0\42\3\60\11"+
    "\21\0\3\3\1\11\13\3\12\0\46\3\53\11\15\0"+
    "\10\3\12\0\66\3\32\11\3\3\17\0\4\3\12\0"+
    "\u0166\3\100\11\12\0\25\3\2\11\12\0\50\11\7\0"+
    "\1\11\4\0\10\3\1\0\10\3\1\11\13\0\50\11"+
    "\2\3\4\11\20\0\46\3\71\11\7\3\11\11\1\3"+
    "\45\11\10\0\1\3\10\0\1\11\17\3\12\0\30\3"+
    "\36\11\2\3\26\0\1\3\16\0\111\3\7\11\1\3"+
    "\2\11\1\3\46\11\6\0\3\3\1\0\1\3\2\0"+
    "\1\3\7\0\1\11\1\0\10\3\12\0\246\3\232\11"+
    "\146\3\157\11\21\3\304\11\274\3\57\11\321\3\107\11"+
    "\271\3\71\11\7\3\37\11\1\3\12\0\146\3\36\11"+
    "\2\3\5\0\13\3\60\11\7\0\11\3\4\11\14\3"+
    "\12\0\11\3\25\11\5\3\23\11\160\3\105\11\13\3"+
    "\1\11\56\0\20\3\4\0\15\11\100\3\2\11\36\3"+
    "\355\11\23\3\363\11\15\3\37\11\121\3\u018c\11\4\3"+
    "\153\11\5\3\15\11\3\3\11\11\7\3\12\11\3\3"+
    "\2\0\1\3\4\0\301\3\5\0\3\3\26\0\2\3"+
    "\7\0\36\3\4\0\224\3\3\0\273\3\125\11\1\3"+
    "\107\11\1\3\2\11\2\3\1\11\2\3\2\11\2\3"+
    "\4\11\1\3\14\11\1\3\1\11\1\3\7\11\1\3"+
    "\101\11\1\3\4\11\2\3\10\11\1\3\7\11\1\3"+
    "\34\11\1\3\4\11\1\3\5\11\1\3\1\11\3\3"+
    "\7\11\1\3\u0154\11\2\3\31\11\1\3\31\11\1\3"+
    "\37\11\1\3\31\11\1\3\37\11\1\3\31\11\1\3"+
    "\37\11\1\3\31\11\1\3\37\11\1\3\31\11\1\3"+
    "\10\11\2\3\151\0\4\3\62\0\10\3\1\0\16\3"+
    "\1\0\26\3\5\0\1\3\17\0\120\3\7\0\1\3"+
    "\21\0\2\3\7\0\1\3\2\0\1\3\5\0\325\3"+
    "\305\11\13\3\7\0\51\3\104\11\7\0\5\3\12\0"+
    "\246\3\4\11\1\3\33\11\1\3\2\11\1\3\1\11"+
    "\2\3\1\11\1\3\12\11\1\3\4\11\1\3\1\11"+
    "\1\3\1\11\6\3\1\11\4\3\1\11\1\3\1\11"+
    "\1\3\1\11\1\3\3\11\1\3\2\11\1\3\1\11"+
    "\2\3\1\11\1\3\1\11\1\3\1\11\1\3\1\11"+
    "\1\3\1\11\1\3\2\11\1\3\1\11\2\3\4\11"+
    "\1\3\7\11\1\3\4\11\1\3\4\11\1\3\1\11"+
    "\1\3\12\11\1\3\21\11\5\3\3\11\1\3\5\11"+
    "\1\3\21\11\104\3\327\11\51\3\65\11\13\3\336\11"+
    "\2\3\u0182\11\16\3\u0131\11\37\3\36\11\343\3\1\0"+
    "\36\3\140\0\200\3\360\0\20\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\1\2\1\3\1\0\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\17\1\20\1\21\1\22\1\23\2\4\1\24\1\0"+
    "\1\25\15\4\1\26\1\27\1\30\1\31\1\32\6\0"+
    "\1\33\1\0\1\4\1\34\1\35\1\36\1\37\2\40"+
    "\1\41\1\1\1\42\1\40\1\43\1\44\1\45\1\4"+
    "\1\46\1\47\10\4\1\50\12\4\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\56\1\57\1\0\7\56"+
    "\1\0\1\4\2\0\2\60\1\61\10\4\1\62\11\4"+
    "\1\56\1\63\1\64\1\65\1\66\1\67\1\70\1\0"+
    "\1\4\1\0\1\40\1\60\1\71\1\4\1\72\2\4"+
    "\1\73\2\4\1\74\7\4\1\75\1\0\1\4\1\76"+
    "\1\77\2\4\1\100\2\4\1\101\1\102\3\4\1\0"+
    "\1\4\1\103\1\104\1\105\1\106\1\107\1\110\1\4"+
    "\1\111\3\4\1\112\30\4\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\253\0\u0156"+
    "\0\u018f\0\u01c8\0\253\0\253\0\253\0\u0201\0\u023a\0\253"+
    "\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357\0\253\0\u0390\0\u03c9"+
    "\0\u0402\0\u043b\0\u0474\0\253\0\u04ad\0\253\0\u04e6\0\u051f"+
    "\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675\0\u06ae\0\u06e7"+
    "\0\u0720\0\u0759\0\u0792\0\253\0\253\0\u07cb\0\253\0\253"+
    "\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\253\0\u095a"+
    "\0\u0993\0\253\0\253\0\253\0\253\0\253\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\253\0\u0a77\0\253\0\253\0\253\0\u0ab0\0\u0993"+
    "\0\253\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f"+
    "\0\u0c78\0\u0993\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce"+
    "\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\253\0\253\0\253\0\253"+
    "\0\253\0\u0eeb\0\253\0\u0876\0\u0876\0\u0f24\0\u0f5d\0\u0f96"+
    "\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e"+
    "\0\u1197\0\u11d0\0\u1209\0\u1125\0\u1242\0\u127b\0\u12b4\0\u12ed"+
    "\0\u1326\0\u135f\0\u1398\0\u13d1\0\u1125\0\u140a\0\u1443\0\u147c"+
    "\0\u14b5\0\u14ee\0\u1527\0\u1560\0\u1599\0\u15d2\0\253\0\u0876"+
    "\0\u0876\0\u0876\0\u0876\0\u0876\0\u0876\0\u160b\0\u1644\0\u167d"+
    "\0\u16b6\0\u16ef\0\u1644\0\u1728\0\u1644\0\u1761\0\u179a\0\u1644"+
    "\0\u17d3\0\u180c\0\u1644\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u1929"+
    "\0\u1962\0\u199b\0\u1644\0\u19d4\0\u1a0d\0\u1a0d\0\u1a0d\0\u1a46"+
    "\0\u1a7f\0\u1a0d\0\u1ab8\0\u1af1\0\u1a0d\0\u1a0d\0\u1b2a\0\u1b63"+
    "\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c0e\0\u1c0e\0\u1c0e\0\u1c0e\0\u1c0e"+
    "\0\u1c0e\0\u1c47\0\253\0\u1c80\0\u1cb9\0\u1cf2\0\u1cf2\0\u1d2b"+
    "\0\u1d64\0\u1d9d\0\u1dd6\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3"+
    "\0\u1f2c\0\u1f65\0\u1f9e\0\u1fd7\0\u2010\0\u2049\0\u2082\0\u20bb"+
    "\0\u20f4\0\u212d\0\u2166\0\u219f\0\u21d8\0\u2211\0\u224a\0\u2283";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\4\1\0\1\5\1\4\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\2\11\1\33\1\11\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\2\11\1\45"+
    "\1\11\1\46\2\11\1\47\1\50\1\51\1\11\1\52"+
    "\1\53\1\11\1\54\1\0\1\55\2\56\1\57\1\56"+
    "\1\0\2\56\1\60\30\56\1\61\30\56\2\62\1\57"+
    "\1\62\1\0\2\62\1\63\3\62\1\64\24\62\1\65"+
    "\14\62\1\66\2\62\1\66\1\62\1\66\4\62\1\66"+
    "\1\62\73\0\1\4\116\0\1\67\105\0\1\70\23\0"+
    "\1\11\10\0\1\71\12\0\2\11\4\0\5\71\3\0"+
    "\24\71\33\0\1\72\70\0\1\73\70\0\1\74\70\0"+
    "\1\75\64\0\1\76\1\77\61\0\1\100\4\0\1\101"+
    "\4\0\1\102\62\0\1\103\70\0\1\103\1\0\2\25"+
    "\73\0\1\104\70\0\1\105\70\0\1\106\40\0\1\11"+
    "\10\0\1\71\12\0\2\11\4\0\2\71\1\107\2\71"+
    "\3\0\24\71\3\0\1\11\10\0\1\71\12\0\2\11"+
    "\4\0\4\71\1\110\3\0\24\71\60\0\1\111\13\0"+
    "\1\11\10\0\1\71\12\0\2\11\4\0\5\71\3\0"+
    "\21\71\1\112\2\71\3\0\1\11\10\0\1\71\12\0"+
    "\2\11\4\0\5\71\3\0\16\71\1\113\5\71\3\0"+
    "\1\11\10\0\1\71\12\0\2\11\4\0\5\71\3\0"+
    "\7\71\1\114\4\71\1\115\7\71\3\0\1\11\10\0"+
    "\1\71\12\0\2\11\4\0\5\71\3\0\14\71\1\116"+
    "\7\71\3\0\1\11\10\0\1\71\12\0\2\11\4\0"+
    "\5\71\3\0\12\71\1\117\10\71\1\120\3\0\1\11"+
    "\10\0\1\71\12\0\2\11\4\0\5\71\3\0\12\71"+
    "\1\121\11\71\3\0\1\11\10\0\1\71\12\0\2\11"+
    "\4\0\5\71\3\0\5\71\1\122\5\71\1\123\10\71"+
    "\3\0\1\11\10\0\1\71\12\0\2\11\4\0\5\71"+
    "\3\0\14\71\1\124\7\71\3\0\1\11\10\0\1\71"+
    "\12\0\2\11\4\0\5\71\3\0\16\71\1\125\5\71"+
    "\3\0\1\11\10\0\1\71\12\0\2\11\4\0\5\71"+
    "\3\0\4\71\1\126\17\71\3\0\1\11\10\0\1\71"+
    "\12\0\2\11\4\0\5\71\3\0\2\71\1\127\4\71"+
    "\1\130\1\131\7\71\1\132\3\71\3\0\1\11\10\0"+
    "\1\71\12\0\2\11\4\0\5\71\3\0\13\71\1\133"+
    "\10\71\3\0\1\11\10\0\1\71\12\0\2\11\4\0"+
    "\5\71\3\0\14\71\1\134\7\71\3\0\2\56\1\0"+
    "\1\56\1\0\2\56\1\0\30\56\1\0\30\56\7\0"+
    "\1\135\30\0\1\136\14\0\1\137\2\0\1\140\1\0"+
    "\1\141\6\0\2\142\1\57\1\142\1\0\2\142\1\0"+
    "\3\142\1\143\24\142\1\0\30\142\7\0\1\144\3\0"+
    "\1\144\24\0\1\144\14\0\1\144\2\0\1\144\1\0"+
    "\1\144\4\0\1\144\10\0\1\144\3\0\1\145\24\0"+
    "\1\144\14\0\1\144\2\0\1\144\1\0\1\144\4\0"+
    "\1\144\1\0\7\146\1\147\3\146\1\150\24\146\1\151"+
    "\14\146\1\152\2\146\1\153\1\146\1\154\4\146\1\144"+
    "\1\146\2\142\1\57\1\142\1\0\2\142\1\144\3\142"+
    "\1\145\24\142\1\144\14\142\1\155\2\142\1\155\1\142"+
    "\1\155\4\142\1\155\1\142\46\0\1\156\22\0\1\71"+
    "\10\0\1\157\12\0\2\71\4\0\5\157\3\0\24\157"+
    "\27\0\2\77\43\0\16\160\1\161\52\160\2\101\1\4"+
    "\1\101\1\5\64\101\24\0\1\162\1\163\43\0\1\71"+
    "\10\0\1\157\12\0\2\71\4\0\1\157\1\164\3\157"+
    "\3\0\24\157\3\0\1\71\10\0\1\157\12\0\2\71"+
    "\4\0\5\157\3\0\20\157\1\165\3\157\3\0\1\71"+
    "\10\0\1\157\12\0\2\71\4\0\5\157\3\0\4\157"+
    "\1\166\17\157\3\0\1\71\10\0\1\157\12\0\2\71"+
    "\4\0\5\157\3\0\1\167\23\157\3\0\1\71\10\0"+
    "\1\157\12\0\2\71\4\0\5\157\3\0\13\157\1\170"+
    "\10\157\3\0\1\71\10\0\1\157\12\0\2\71\4\0"+
    "\5\157\3\0\21\157\1\171\2\157\3\0\1\71\10\0"+
    "\1\157\12\0\2\71\4\0\5\157\3\0\17\157\1\172"+
    "\4\157\3\0\1\71\10\0\1\157\12\0\2\71\4\0"+
    "\5\157\3\0\20\157\1\173\3\157\3\0\1\71\10\0"+
    "\1\157\12\0\2\71\4\0\5\157\3\0\14\157\1\174"+
    "\7\157\3\0\1\71\10\0\1\157\12\0\2\71\4\0"+
    "\5\157\3\0\20\157\1\175\3\157\3\0\1\71\10\0"+
    "\1\157\12\0\2\71\4\0\5\157\3\0\13\157\1\176"+
    "\10\157\3\0\1\71\10\0\1\157\12\0\2\71\4\0"+
    "\5\157\3\0\10\157\1\177\13\157\3\0\1\71\10\0"+
    "\1\157\12\0\2\71\4\0\5\157\3\0\20\157\1\200"+
    "\3\157\3\0\1\71\10\0\1\157\12\0\2\71\4\0"+
    "\5\157\3\0\1\201\23\157\3\0\1\71\10\0\1\157"+
    "\12\0\2\71\4\0\5\157\3\0\14\157\1\202\7\157"+
    "\3\0\1\71\10\0\1\157\12\0\2\71\4\0\5\157"+
    "\3\0\6\157\1\203\15\157\3\0\1\71\10\0\1\157"+
    "\12\0\2\71\4\0\5\157\3\0\1\204\23\157\3\0"+
    "\1\71\10\0\1\157\12\0\2\71\4\0\5\157\3\0"+
    "\17\157\1\205\4\157\3\0\1\71\10\0\1\157\12\0"+
    "\2\71\4\0\5\157\3\0\10\157\1\206\13\157\3\0"+
    "\2\142\1\57\1\142\1\0\2\142\1\0\3\142\1\207"+
    "\24\142\1\0\30\142\13\0\1\207\64\0\1\144\3\0"+
    "\1\210\24\0\1\144\14\0\1\144\2\0\1\144\1\0"+
    "\1\144\4\0\1\144\10\0\1\144\3\0\1\211\24\0"+
    "\1\144\14\0\1\144\2\0\1\144\1\0\1\144\4\0"+
    "\1\144\10\0\1\144\3\0\1\212\24\0\1\144\14\0"+
    "\1\144\2\0\1\144\1\0\1\144\4\0\1\144\10\0"+
    "\1\144\3\0\1\213\24\0\1\144\14\0\1\144\2\0"+
    "\1\144\1\0\1\144\4\0\1\144\10\0\1\144\3\0"+
    "\1\214\24\0\1\144\14\0\1\144\2\0\1\144\1\0"+
    "\1\144\4\0\1\144\10\0\1\144\3\0\1\215\24\0"+
    "\1\144\14\0\1\144\2\0\1\144\1\0\1\144\4\0"+
    "\1\144\1\0\2\142\1\57\1\142\1\0\2\142\1\144"+
    "\3\142\1\144\24\142\1\144\14\142\1\155\2\142\1\155"+
    "\1\142\1\155\4\142\1\155\1\142\47\0\1\216\21\0"+
    "\1\157\10\0\1\217\12\0\2\157\4\0\5\217\3\0"+
    "\24\217\3\0\16\160\1\220\52\160\16\0\1\161\4\0"+
    "\1\4\67\0\1\221\1\0\2\222\65\0\1\221\1\0"+
    "\2\163\43\0\1\157\10\0\1\217\12\0\2\157\4\0"+
    "\5\217\3\0\14\217\1\223\7\217\3\0\1\157\10\0"+
    "\1\217\12\0\2\157\4\0\5\217\3\0\1\224\23\217"+
    "\3\0\1\157\10\0\1\217\12\0\2\157\4\0\5\217"+
    "\3\0\16\217\1\225\5\217\3\0\1\157\10\0\1\217"+
    "\12\0\2\157\4\0\5\217\3\0\17\217\1\226\4\217"+
    "\3\0\1\157\10\0\1\217\12\0\2\157\4\0\5\217"+
    "\3\0\1\217\1\227\22\217\3\0\1\157\10\0\1\217"+
    "\12\0\2\157\4\0\5\217\3\0\4\217\1\230\17\217"+
    "\3\0\1\157\10\0\1\217\12\0\2\157\4\0\5\217"+
    "\3\0\4\217\1\231\17\217\3\0\1\157\10\0\1\217"+
    "\12\0\2\157\4\0\5\217\3\0\1\232\23\217\3\0"+
    "\1\157\10\0\1\217\12\0\2\157\4\0\5\217\3\0"+
    "\6\217\1\233\15\217\3\0\1\157\10\0\1\217\12\0"+
    "\2\157\4\0\5\217\3\0\13\217\1\234\10\217\3\0"+
    "\1\157\10\0\1\217\12\0\2\157\4\0\5\217\3\0"+
    "\21\217\1\235\2\217\3\0\1\157\10\0\1\217\12\0"+
    "\2\157\4\0\5\217\3\0\13\217\1\236\10\217\3\0"+
    "\1\157\10\0\1\217\12\0\2\157\4\0\5\217\3\0"+
    "\16\217\1\237\5\217\3\0\1\157\10\0\1\217\12\0"+
    "\2\157\4\0\5\217\3\0\13\217\1\240\10\217\3\0"+
    "\1\157\10\0\1\217\12\0\2\157\4\0\5\217\3\0"+
    "\20\217\1\241\3\217\3\0\1\157\10\0\1\217\12\0"+
    "\2\157\4\0\5\217\3\0\10\217\1\242\13\217\3\0"+
    "\1\157\10\0\1\217\12\0\2\157\4\0\5\217\3\0"+
    "\3\217\1\243\20\217\55\0\1\244\16\0\1\217\10\0"+
    "\1\245\12\0\2\217\4\0\5\245\3\0\24\245\3\0"+
    "\16\160\1\220\4\160\1\4\45\160\22\0\1\221\1\0"+
    "\2\221\67\0\2\222\43\0\1\217\10\0\1\245\12\0"+
    "\2\217\4\0\5\245\3\0\11\245\1\246\12\245\3\0"+
    "\1\217\10\0\1\245\12\0\2\217\4\0\5\245\3\0"+
    "\20\245\1\247\3\245\3\0\1\217\10\0\1\245\12\0"+
    "\2\217\4\0\5\245\3\0\12\245\1\250\11\245\3\0"+
    "\1\217\10\0\1\245\12\0\2\217\4\0\5\245\3\0"+
    "\16\245\1\251\5\245\3\0\1\217\10\0\1\245\12\0"+
    "\2\217\4\0\5\245\3\0\20\245\1\252\3\245\3\0"+
    "\1\217\10\0\1\245\12\0\2\217\4\0\5\245\3\0"+
    "\20\245\1\253\3\245\3\0\1\217\10\0\1\245\12\0"+
    "\2\217\4\0\5\245\3\0\16\245\1\254\5\245\3\0"+
    "\1\217\10\0\1\245\12\0\2\217\4\0\5\245\3\0"+
    "\5\245\1\255\16\245\3\0\1\217\10\0\1\245\12\0"+
    "\2\217\4\0\5\245\3\0\20\245\1\256\3\245\3\0"+
    "\1\217\10\0\1\245\12\0\2\217\4\0\5\245\3\0"+
    "\4\245\1\257\17\245\3\0\1\217\10\0\1\245\12\0"+
    "\2\217\4\0\5\245\3\0\10\245\1\260\13\245\3\0"+
    "\1\217\10\0\1\245\12\0\2\217\4\0\5\245\3\0"+
    "\6\245\1\261\15\245\60\0\1\262\13\0\1\245\10\0"+
    "\1\263\12\0\2\245\4\0\5\263\3\0\24\263\3\0"+
    "\1\245\10\0\1\263\12\0\2\245\4\0\5\263\3\0"+
    "\4\263\1\264\17\263\3\0\1\245\10\0\1\263\12\0"+
    "\2\245\4\0\5\263\3\0\13\263\1\265\10\263\3\0"+
    "\1\245\10\0\1\263\12\0\2\245\4\0\5\263\3\0"+
    "\5\263\1\266\16\263\3\0\1\245\10\0\1\263\12\0"+
    "\2\245\4\0\5\263\3\0\13\263\1\267\10\263\3\0"+
    "\1\245\10\0\1\263\12\0\2\245\4\0\5\263\3\0"+
    "\3\263\1\270\20\263\3\0\1\245\10\0\1\263\12\0"+
    "\2\245\4\0\5\263\3\0\2\263\1\271\21\263\3\0"+
    "\1\245\10\0\1\263\12\0\2\245\4\0\5\263\3\0"+
    "\13\263\1\272\10\263\51\0\1\273\22\0\1\263\10\0"+
    "\1\274\12\0\2\263\4\0\5\274\3\0\24\274\3\0"+
    "\1\263\10\0\1\274\12\0\2\263\4\0\5\274\3\0"+
    "\4\274\1\275\17\274\3\0\1\274\10\0\1\276\12\0"+
    "\2\274\4\0\5\276\3\0\24\276\3\0\1\274\10\0"+
    "\1\276\12\0\2\274\4\0\5\276\3\0\3\276\1\277"+
    "\20\276\3\0\1\276\10\0\1\300\12\0\2\276\4\0"+
    "\5\300\3\0\24\300\3\0\1\300\10\0\1\301\12\0"+
    "\2\300\4\0\5\301\3\0\24\301\3\0\1\301\10\0"+
    "\1\302\12\0\2\301\4\0\5\302\3\0\24\302\3\0"+
    "\1\302\10\0\1\303\12\0\2\302\4\0\5\303\3\0"+
    "\24\303\3\0\1\303\10\0\1\304\12\0\2\303\4\0"+
    "\5\304\3\0\24\304\3\0\1\304\10\0\1\305\12\0"+
    "\2\304\4\0\5\305\3\0\24\305\3\0\1\305\10\0"+
    "\1\306\12\0\2\305\4\0\5\306\3\0\24\306\3\0"+
    "\1\306\10\0\1\307\12\0\2\306\4\0\5\307\3\0"+
    "\24\307\3\0\1\307\10\0\1\310\12\0\2\307\4\0"+
    "\5\310\3\0\24\310\3\0\1\310\10\0\1\311\12\0"+
    "\2\310\4\0\5\311\3\0\24\311\3\0\1\311\10\0"+
    "\1\312\12\0\2\311\4\0\5\312\3\0\24\312\3\0"+
    "\1\312\10\0\1\313\12\0\2\312\4\0\5\313\3\0"+
    "\24\313\3\0\1\313\10\0\1\314\12\0\2\313\4\0"+
    "\5\314\3\0\24\314\3\0\1\314\10\0\1\315\12\0"+
    "\2\314\4\0\5\315\3\0\24\315\3\0\1\315\10\0"+
    "\1\316\12\0\2\315\4\0\5\316\3\0\24\316\3\0"+
    "\1\316\10\0\1\317\12\0\2\316\4\0\5\317\3\0"+
    "\24\317\3\0\1\317\10\0\1\320\12\0\2\317\4\0"+
    "\5\320\3\0\24\320\3\0\1\320\10\0\1\321\12\0"+
    "\2\320\4\0\5\321\3\0\24\321\3\0\1\321\10\0"+
    "\1\322\12\0\2\321\4\0\5\322\3\0\24\322\3\0"+
    "\1\322\10\0\1\323\12\0\2\322\4\0\5\323\3\0"+
    "\24\323\3\0\1\323\10\0\1\324\12\0\2\323\4\0"+
    "\5\324\3\0\24\324\3\0\1\324\10\0\1\325\12\0"+
    "\2\324\4\0\5\325\3\0\24\325\3\0\1\325\10\0"+
    "\1\326\12\0\2\325\4\0\5\326\3\0\24\326\3\0"+
    "\1\326\10\0\1\327\12\0\2\326\4\0\5\327\3\0"+
    "\24\327\3\0\1\327\1\330\1\0\2\330\1\0\3\330"+
    "\1\327\12\330\2\327\4\330\5\327\3\330\24\327\5\330"+
    "\1\0\2\330\1\0\63\330";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8892];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\1\0\2\1\3\11\2\1"+
    "\1\11\5\1\1\11\5\1\1\11\1\0\1\11\15\1"+
    "\2\11\1\1\2\11\6\0\1\11\1\0\1\1\5\11"+
    "\3\1\1\11\1\1\3\11\2\1\1\11\23\1\5\11"+
    "\1\1\1\11\2\1\1\0\7\1\1\0\1\1\2\0"+
    "\25\1\1\11\6\1\1\0\1\1\1\0\23\1\1\0"+
    "\15\1\1\0\10\1\1\11\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    private final List<Symbol> symbols;
    private final ArrayList<ErroAnalisado> errors;
    private ComplexSymbolFactory symbolFactory;
    private Character caracterRead;
    StringBuffer string = new StringBuffer();
    Symbol stringSymbol;

    public Lexer(java.io.Reader in, ComplexSymbolFactory symbolFactory){
	this(in);
	this.symbolFactory = symbolFactory;
    }

    public void executar() throws IOException {
        while(next_token().sym != sym.EOF);
    }

    public ArrayList<ErroAnalisado> getErros() {
        return this.errors;
    }

    public int countErros() {
        return this.errors.size();
    }

    private void addErro(String erro) {
        Location left = new Location(yyline+1,yycolumn+1,((int)yychar));
        Location right = new Location(yyline+1,yycolumn+yylength(), ((int)yychar+yylength()));
        Symbol symbol = symbolFactory.newSymbol("ERRO LÉXICO -> ", sym.error, left, right);
        this.errors.add(new ErroAnalisado("ERRO LÉXICO >>> " + erro, symbol));
    }
    
    public List<Symbol> getSymbols() {
        return this.symbols;
    }

    private void addSymbol(Symbol symbol) {
        this.symbols.add(symbol);
    }

    private Symbol symbol(int sym, String name) {
        return symbol(name, sym, yytext());
    }

    private Symbol symbol(String name, int sym) {
        Symbol symbol = symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,((int)yychar)), new Location(yyline+1,yycolumn+yylength(),((int)yychar)+yylength()));
        addSymbol(symbol);
        return symbol;
    }

    private Symbol symbol(String name, int sym, Object val) {
        Location left = new Location(yyline+1,yycolumn+1,((int)yychar));
        Location right = new Location(yyline+1,yycolumn+yylength(), ((int)yychar)+yylength());
        Symbol symbol = symbolFactory.newSymbol(name, sym, left, right,val);
        addSymbol(symbol);
        return symbol;
    }

    private Symbol symbol(String name, int sym, Object val,int buflength) {
        Location left = new Location(yyline+1,yycolumn+yylength()-buflength,((int)yychar)+yylength()-buflength);
        Location right = new Location(yyline+1,yycolumn+yylength(), ((int)yychar)+yylength());
        Symbol symbol = symbolFactory.newSymbol(name, sym, left, right,val);
        addSymbol(symbol);
        return symbol;
    }
    
    private Symbol symbolEOF(String name, int sym){
        Symbol symbol = symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,((int)yychar)), new Location(yyline+1,yycolumn+yylength(),((int)yychar)+yylength()));
        return symbol;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      this.symbols = new ArrayList<>();
    this.errors = new ArrayList<>();
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbolEOF("EOF", sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignore */
            }
            // fall through
          case 76: break;
          case 2:
            { return symbol(sym.NOT, "NOT");
            }
            // fall through
          case 77: break;
          case 3:
            { string.setLength(0); stringSymbol = symbol("STRING", sym.STRING); yybegin(STRING);
            }
            // fall through
          case 78: break;
          case 4:
            { return symbol("ID", sym.ID, yytext());
            }
            // fall through
          case 79: break;
          case 5:
            { return symbol(sym.MOD, "MOD");
            }
            // fall through
          case 80: break;
          case 6:
            { yybegin(CHAR);
            }
            // fall through
          case 81: break;
          case 7:
            { return symbol(sym.LPAREN, "LPAREN");
            }
            // fall through
          case 82: break;
          case 8:
            { return symbol(sym.RPAREN, "RPAREN");
            }
            // fall through
          case 83: break;
          case 9:
            { return symbol(sym.MULT, "MULT");
            }
            // fall through
          case 84: break;
          case 10:
            { return symbol(sym.PLUS, "PLUS");
            }
            // fall through
          case 85: break;
          case 11:
            { return symbol(sym.COMMA, "COMMA");
            }
            // fall through
          case 86: break;
          case 12:
            { return symbol(sym.MINUS, "MINUS");
            }
            // fall through
          case 87: break;
          case 13:
            { return symbol(sym.DOT, "DOT");
            }
            // fall through
          case 88: break;
          case 14:
            { return symbol(sym.DIV, "DIV");
            }
            // fall through
          case 89: break;
          case 15:
            { return symbol(sym.NUM_INT, "NUM_INT");
            }
            // fall through
          case 90: break;
          case 16:
            { return symbol(sym.SEMICOLON, "SEMICOLON");
            }
            // fall through
          case 91: break;
          case 17:
            { return symbol(sym.LT, "LT");
            }
            // fall through
          case 92: break;
          case 18:
            { return symbol(sym.EQ, "EQ");
            }
            // fall through
          case 93: break;
          case 19:
            { return symbol(sym.GT, "GT");
            }
            // fall through
          case 94: break;
          case 20:
            { return symbol(sym.LBRACK, "LBRACK");
            }
            // fall through
          case 95: break;
          case 21:
            { return symbol(sym.RBRACK, "RBRACK");
            }
            // fall through
          case 96: break;
          case 22:
            { return symbol(sym.LBRACE, "LBRACE");
            }
            // fall through
          case 97: break;
          case 23:
            { return symbol(sym.RBRACE, "RBRACE");
            }
            // fall through
          case 98: break;
          case 24:
            { string.append( yytext() );
            }
            // fall through
          case 99: break;
          case 25:
            { yybegin(YYINITIAL);
                                        this.addErro("Linha " + (yyline+1) + ", coluna " + yycolumn + ": Aspas sem fechamento.");
            }
            // fall through
          case 100: break;
          case 26:
            { yybegin(YYINITIAL); 
                                        stringSymbol.value = string.toString();
                                        return stringSymbol;
            }
            // fall through
          case 101: break;
          case 27:
            { return symbol(sym.NOTEQ, "NOTEQ");
            }
            // fall through
          case 102: break;
          case 28:
            { return symbol(sym.MODEQ, "MODEQ");
            }
            // fall through
          case 103: break;
          case 29:
            { return symbol(sym.MULTEQ, "MULTEQ");
            }
            // fall through
          case 104: break;
          case 30:
            { return symbol(sym.PLUSEQ, "PLUSEQ");
            }
            // fall through
          case 105: break;
          case 31:
            { return symbol(sym.MINUSEQ, "MINUSEQ");
            }
            // fall through
          case 106: break;
          case 32:
            { this.addErro("Linha " + (yyline+1) + ", coluna " + yycolumn + ": " + yytext().toUpperCase() + " não é um número.");
            }
            // fall through
          case 107: break;
          case 33:
            { this.addErro("Linha " + (yyline+1) + ", coluna " + yycolumn + ": Falta fechar o comentário.");
            }
            // fall through
          case 108: break;
          case 34:
            { return symbol(sym.DIVEQ, "DIVEQ");
            }
            // fall through
          case 109: break;
          case 35:
            { return symbol(sym.LTEQ, "LTEQ");
            }
            // fall through
          case 110: break;
          case 36:
            { return symbol(sym.EQEQ, "EQEQ");
            }
            // fall through
          case 111: break;
          case 37:
            { return symbol(sym.GTEQ, "GTEQ");
            }
            // fall through
          case 112: break;
          case 38:
            { return symbol(sym.OR, "OR");
            }
            // fall through
          case 113: break;
          case 39:
            { return symbol(sym.CRLF, "CRLF");
            }
            // fall through
          case 114: break;
          case 40:
            { return symbol(sym.IF, "IF");
            }
            // fall through
          case 115: break;
          case 41:
            { string.append('\"');
            }
            // fall through
          case 116: break;
          case 42:
            { string.append('\\');
            }
            // fall through
          case 117: break;
          case 43:
            { string.append('\n');
            }
            // fall through
          case 118: break;
          case 44:
            { string.append('\r');
            }
            // fall through
          case 119: break;
          case 45:
            { string.append('\t');
            }
            // fall through
          case 120: break;
          case 46:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 121: break;
          case 47:
            { yybegin(YYINITIAL); 
                                        return symbol("CARACTERE", sym.CHAR, " " + yytext().charAt(0));
            }
            // fall through
          case 122: break;
          case 48:
            { return symbol(sym.NUM_FLOAT, "NUM_FLOAT");
            }
            // fall through
          case 123: break;
          case 49:
            { return symbol(sym.AND, "AND");
            }
            // fall through
          case 124: break;
          case 50:
            { return symbol(sym.INT, "INT");
            }
            // fall through
          case 125: break;
          case 51:
            { yybegin(YYINITIAL); 
                                        caracterRead = '\"'; 
                                        return symbol("CARACTERE", sym.CHAR, caracterRead.toString());
            }
            // fall through
          case 126: break;
          case 52:
            { yybegin(YYINITIAL); 
                                        caracterRead = '\''; 
                                        return symbol("CARACTERE", sym.CHAR, caracterRead.toString());
            }
            // fall through
          case 127: break;
          case 53:
            { yybegin(YYINITIAL); 
                                        caracterRead = '\\'; 
                                        return symbol("CARACTERE", sym.CHAR, caracterRead.toString());
            }
            // fall through
          case 128: break;
          case 54:
            { yybegin(YYINITIAL); 
                                        caracterRead = '\n'; 
                                        return symbol("CARACTERE", sym.CHAR, caracterRead.toString());
            }
            // fall through
          case 129: break;
          case 55:
            { yybegin(YYINITIAL); 
                                        caracterRead = '\r'; 
                                        return symbol("CARACTERE", sym.CHAR, caracterRead.toString());
            }
            // fall through
          case 130: break;
          case 56:
            { yybegin(YYINITIAL); 
                                        caracterRead = '\t';
                                        return symbol("CARACTERE", sym.CHAR, caracterRead.toString());
            }
            // fall through
          case 131: break;
          case 57:
            { return symbol(sym.AUTO, "AUTO");
            }
            // fall through
          case 132: break;
          case 58:
            { return symbol(sym.CHAR, "CHAR");
            }
            // fall through
          case 133: break;
          case 59:
            { return symbol(sym.ELSE, "ELSE");
            }
            // fall through
          case 134: break;
          case 60:
            { return symbol(sym.LONG, "LONG");
            }
            // fall through
          case 135: break;
          case 61:
            { return symbol(sym.VOID, "VOID");
            }
            // fall through
          case 136: break;
          case 62:
            { return symbol(sym.BREAK, "BREAK");
            }
            // fall through
          case 137: break;
          case 63:
            { return symbol(sym.CONST, "CONST");
            }
            // fall through
          case 138: break;
          case 64:
            { return symbol(sym.FLOAT, "FLOAT");
            }
            // fall through
          case 139: break;
          case 65:
            { return symbol(sym.SCANF, "SCANF");
            }
            // fall through
          case 140: break;
          case 66:
            { return symbol(sym.SHORT, "SHORT");
            }
            // fall through
          case 141: break;
          case 67:
            { return symbol(sym.DOUBLE, "DOUBLE");
            }
            // fall through
          case 142: break;
          case 68:
            { return symbol(sym.EXTERN, "EXTERN");
            }
            // fall through
          case 143: break;
          case 69:
            { return symbol(sym.PRINTF, "PRINTF");
            }
            // fall through
          case 144: break;
          case 70:
            { return symbol(sym.RETURN, "RETURN");
            }
            // fall through
          case 145: break;
          case 71:
            { return symbol(sym.SIGNED, "SIGNED");
            }
            // fall through
          case 146: break;
          case 72:
            { return symbol(sym.STATIC, "STATIC");
            }
            // fall through
          case 147: break;
          case 73:
            { return symbol(sym.DEFINE, "DEFINE");
            }
            // fall through
          case 148: break;
          case 74:
            { return symbol(sym.UNSIGNED, "UNSIGNED");
            }
            // fall through
          case 149: break;
          case 75:
            { this.addErro("Linha " + (yyline+1) + ", coluna " + yycolumn + ": Identificador " + yytext().toUpperCase() + " excedeu o limite de caracteres.");
            }
            // fall through
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
