
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.ufes.analisador.lexico.jflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 48;
  public static final int GTEQ = 36;
  public static final int SHORT = 13;
  public static final int SCANF = 17;
  public static final int MULT = 42;
  public static final int CONST = 5;
  public static final int CHAR = 7;
  public static final int LTEQ = 35;
  public static final int MODEQ = 49;
  public static final int DOUBLE = 9;
  public static final int LPAREN = 21;
  public static final int NUM_INT = 53;
  public static final int INT = 12;
  public static final int MINUS = 41;
  public static final int STATIC = 3;
  public static final int RPAREN = 22;
  public static final int DEFINE = 50;
  public static final int AND = 38;
  public static final int NOT = 33;
  public static final int SEMICOLON = 27;
  public static final int LT = 32;
  public static final int OR = 39;
  public static final int COMMA = 28;
  public static final int DIV = 43;
  public static final int PLUSEQ = 45;
  public static final int MINUSEQ = 46;
  public static final int EXTERN = 4;
  public static final int PLUS = 40;
  public static final int IF = 19;
  public static final int ID = 51;
  public static final int DOT = 29;
  public static final int CRLF = 54;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int error = 1;
  public static final int EQEQ = 34;
  public static final int MULTEQ = 47;
  public static final int MOD = 44;
  public static final int UNSIGNED = 11;
  public static final int AUTO = 2;
  public static final int BREAK = 18;
  public static final int VOID = 6;
  public static final int EQ = 30;
  public static final int PRINTF = 16;
  public static final int LBRACK = 25;
  public static final int LBRACE = 23;
  public static final int ELSE = 20;
  public static final int SIGNED = 10;
  public static final int RBRACK = 26;
  public static final int FLOAT = 8;
  public static final int RBRACE = 24;
  public static final int LONG = 14;
  public static final int STRING = 55;
  public static final int NUM_FLOAT = 52;
  public static final int GT = 31;
  public static final int NOTEQ = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AUTO",
  "STATIC",
  "EXTERN",
  "CONST",
  "VOID",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "SIGNED",
  "UNSIGNED",
  "INT",
  "SHORT",
  "LONG",
  "RETURN",
  "PRINTF",
  "SCANF",
  "BREAK",
  "IF",
  "ELSE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "EQ",
  "GT",
  "LT",
  "NOT",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "DEFINE",
  "ID",
  "NUM_FLOAT",
  "NUM_INT",
  "CRLF",
  "STRING"
  };
}

